#include "format_utils.hpp"

namespace duckdb {

// Static map for string-to-enum conversion (includes aliases)
const std::unordered_map<std::string, TestResultFormat> &GetFormatMap() {
	static const std::unordered_map<std::string, TestResultFormat> map = {
	    // Primary names
	    {"unknown", TestResultFormat::UNKNOWN},
	    {"auto", TestResultFormat::AUTO},
	    {"pytest_json", TestResultFormat::PYTEST_JSON},
	    {"gotest_json", TestResultFormat::GOTEST_JSON},
	    {"eslint_json", TestResultFormat::ESLINT_JSON},
	    {"pytest_text", TestResultFormat::PYTEST_TEXT},
	    {"make_error", TestResultFormat::MAKE_ERROR},
	    {"generic_lint", TestResultFormat::GENERIC_LINT},
	    {"duckdb_test", TestResultFormat::DUCKDB_TEST},
	    {"rubocop_json", TestResultFormat::RUBOCOP_JSON},
	    {"cargo_test_json", TestResultFormat::CARGO_TEST_JSON},
	    {"swiftlint_json", TestResultFormat::SWIFTLINT_JSON},
	    {"phpstan_json", TestResultFormat::PHPSTAN_JSON},
	    {"shellcheck_json", TestResultFormat::SHELLCHECK_JSON},
	    {"stylelint_json", TestResultFormat::STYLELINT_JSON},
	    {"clippy_json", TestResultFormat::CLIPPY_JSON},
	    {"markdownlint_json", TestResultFormat::MARKDOWNLINT_JSON},
	    {"yamllint_json", TestResultFormat::YAMLLINT_JSON},
	    {"bandit_json", TestResultFormat::BANDIT_JSON},
	    {"spotbugs_json", TestResultFormat::SPOTBUGS_JSON},
	    {"ktlint_json", TestResultFormat::KTLINT_JSON},
	    {"hadolint_json", TestResultFormat::HADOLINT_JSON},
	    {"lintr_json", TestResultFormat::LINTR_JSON},
	    {"sqlfluff_json", TestResultFormat::SQLFLUFF_JSON},
	    {"tflint_json", TestResultFormat::TFLINT_JSON},
	    {"kube_score_json", TestResultFormat::KUBE_SCORE_JSON},
	    {"cmake_build", TestResultFormat::CMAKE_BUILD},
	    {"python_build", TestResultFormat::PYTHON_BUILD},
	    {"node_build", TestResultFormat::NODE_BUILD},
	    {"cargo_build", TestResultFormat::CARGO_BUILD},
	    {"maven_build", TestResultFormat::MAVEN_BUILD},
	    {"gradle_build", TestResultFormat::GRADLE_BUILD},
	    {"msbuild", TestResultFormat::MSBUILD},
	    {"junit_text", TestResultFormat::JUNIT_TEXT},
	    {"valgrind", TestResultFormat::VALGRIND},
	    {"gdb_lldb", TestResultFormat::GDB_LLDB},
	    {"rspec_text", TestResultFormat::RSPEC_TEXT},
	    {"mocha_chai_text", TestResultFormat::MOCHA_CHAI_TEXT},
	    {"gtest_text", TestResultFormat::GTEST_TEXT},
	    {"nunit_xunit_text", TestResultFormat::NUNIT_XUNIT_TEXT},
	    {"pylint_text", TestResultFormat::PYLINT_TEXT},
	    {"flake8_text", TestResultFormat::FLAKE8_TEXT},
	    {"black_text", TestResultFormat::BLACK_TEXT},
	    {"mypy_text", TestResultFormat::MYPY_TEXT},
	    {"docker_build", TestResultFormat::DOCKER_BUILD},
	    {"bazel_build", TestResultFormat::BAZEL_BUILD},
	    {"isort_text", TestResultFormat::ISORT_TEXT},
	    {"bandit_text", TestResultFormat::BANDIT_TEXT},
	    {"autopep8_text", TestResultFormat::AUTOPEP8_TEXT},
	    {"yapf_text", TestResultFormat::YAPF_TEXT},
	    {"coverage_text", TestResultFormat::COVERAGE_TEXT},
	    {"pytest_cov_text", TestResultFormat::PYTEST_COV_TEXT},
	    {"github_actions_text", TestResultFormat::GITHUB_ACTIONS_TEXT},
	    {"gitlab_ci_text", TestResultFormat::GITLAB_CI_TEXT},
	    {"jenkins_text", TestResultFormat::JENKINS_TEXT},
	    {"drone_ci_text", TestResultFormat::DRONE_CI_TEXT},
	    {"terraform_text", TestResultFormat::TERRAFORM_TEXT},
	    {"ansible_text", TestResultFormat::ANSIBLE_TEXT},
	    {"github_cli", TestResultFormat::GITHUB_CLI},
	    {"clang_tidy_text", TestResultFormat::CLANG_TIDY_TEXT},
	    {"regexp", TestResultFormat::REGEXP},
	    {"junit_xml", TestResultFormat::JUNIT_XML},
	    {"nunit_xml", TestResultFormat::NUNIT_XML},
	    {"checkstyle_xml", TestResultFormat::CHECKSTYLE_XML},
	    {"jsonl", TestResultFormat::JSONL},
	    {"logfmt", TestResultFormat::LOGFMT},
	    {"syslog", TestResultFormat::SYSLOG},
	    {"apache_access", TestResultFormat::APACHE_ACCESS},
	    {"nginx_access", TestResultFormat::NGINX_ACCESS},
	    {"aws_cloudtrail", TestResultFormat::AWS_CLOUDTRAIL},
	    {"gcp_cloud_logging", TestResultFormat::GCP_CLOUD_LOGGING},
	    {"azure_activity", TestResultFormat::AZURE_ACTIVITY},
	    {"python_logging", TestResultFormat::PYTHON_LOGGING},
	    {"log4j", TestResultFormat::LOG4J},
	    {"logrus", TestResultFormat::LOGRUS},
	    {"iptables", TestResultFormat::IPTABLES},
	    {"pf", TestResultFormat::PF_FIREWALL},
	    {"cisco_asa", TestResultFormat::CISCO_ASA},
	    {"vpc_flow", TestResultFormat::VPC_FLOW},
	    {"kubernetes", TestResultFormat::KUBERNETES},
	    {"windows_event", TestResultFormat::WINDOWS_EVENT},
	    {"auditd", TestResultFormat::AUDITD},
	    {"s3_access", TestResultFormat::S3_ACCESS},
	    {"winston", TestResultFormat::WINSTON},
	    {"pino", TestResultFormat::PINO},
	    {"bunyan", TestResultFormat::BUNYAN},
	    {"serilog", TestResultFormat::SERILOG},
	    {"nlog", TestResultFormat::NLOG},
	    {"ruby_logger", TestResultFormat::RUBY_LOGGER},
	    {"rails_log", TestResultFormat::RAILS_LOG},
	    {"strace", TestResultFormat::STRACE},
	    {"gcc_text", TestResultFormat::GCC_TEXT},
	    // Aliases
	    {"ndjson", TestResultFormat::JSONL},
	    {"cloudtrail", TestResultFormat::AWS_CLOUDTRAIL},
	    {"gcp_logging", TestResultFormat::GCP_CLOUD_LOGGING},
	    {"azure_activity_log", TestResultFormat::AZURE_ACTIVITY},
	    {"python_log", TestResultFormat::PYTHON_LOGGING},
	    {"log4j_text", TestResultFormat::LOG4J},
	    {"logback", TestResultFormat::LOG4J},
	    {"logrus_text", TestResultFormat::LOGRUS},
	    {"winston_json", TestResultFormat::WINSTON},
	    {"pino_json", TestResultFormat::PINO},
	    {"bunyan_json", TestResultFormat::BUNYAN},
	    {"serilog_json", TestResultFormat::SERILOG},
	    {"serilog_text", TestResultFormat::SERILOG},
	    {"nlog_text", TestResultFormat::NLOG},
	    {"ruby_log", TestResultFormat::RUBY_LOGGER},
	    {"rails", TestResultFormat::RAILS_LOG},
	    {"netfilter", TestResultFormat::IPTABLES},
	    {"ufw", TestResultFormat::IPTABLES},
	    {"pf_firewall", TestResultFormat::PF_FIREWALL},
	    {"openbsd_pf", TestResultFormat::PF_FIREWALL},
	    {"asa", TestResultFormat::CISCO_ASA},
	    {"vpc_flow_logs", TestResultFormat::VPC_FLOW},
	    {"aws_vpc_flow", TestResultFormat::VPC_FLOW},
	    {"k8s", TestResultFormat::KUBERNETES},
	    {"kube", TestResultFormat::KUBERNETES},
	    {"windows_event_log", TestResultFormat::WINDOWS_EVENT},
	    {"eventlog", TestResultFormat::WINDOWS_EVENT},
	    {"audit", TestResultFormat::AUDITD},
	    {"ssh_auth", TestResultFormat::AUDITD},
	    {"s3_access_log", TestResultFormat::S3_ACCESS},
	    // Linting tool aliases
	    {"pylint", TestResultFormat::PYLINT_TEXT},
	    {"mypy", TestResultFormat::MYPY_TEXT},
	    {"flake8", TestResultFormat::FLAKE8_TEXT},
	    {"black", TestResultFormat::BLACK_TEXT},
	    {"yapf", TestResultFormat::YAPF_TEXT},
	    {"autopep8", TestResultFormat::AUTOPEP8_TEXT},
	    {"clang_tidy", TestResultFormat::CLANG_TIDY_TEXT},
	    {"clang-tidy", TestResultFormat::CLANG_TIDY_TEXT},
	    // Build system aliases
	    {"make", TestResultFormat::MAKE_ERROR},
	    // Compiler diagnostic aliases
	    {"gcc", TestResultFormat::GCC_TEXT},
	    {"g++", TestResultFormat::GCC_TEXT},
	    {"clang", TestResultFormat::GCC_TEXT},
	    {"clang++", TestResultFormat::GCC_TEXT},
	    {"cc", TestResultFormat::GCC_TEXT},
	    {"c++", TestResultFormat::GCC_TEXT},
	    {"gfortran", TestResultFormat::GCC_TEXT},
	    {"gnat", TestResultFormat::GCC_TEXT},
	    {"compiler_diagnostic", TestResultFormat::GCC_TEXT},
	    {"cmake", TestResultFormat::CMAKE_BUILD},
	    {"maven", TestResultFormat::MAVEN_BUILD},
	    {"mvn", TestResultFormat::MAVEN_BUILD},
	    {"gradle", TestResultFormat::GRADLE_BUILD},
	    {"cargo", TestResultFormat::CARGO_BUILD},
	    {"rust", TestResultFormat::CARGO_BUILD},
	    {"node", TestResultFormat::NODE_BUILD},
	    {"npm", TestResultFormat::NODE_BUILD},
	    {"yarn", TestResultFormat::NODE_BUILD},
	    {"pip", TestResultFormat::PYTHON_BUILD},
	    {"setuptools", TestResultFormat::PYTHON_BUILD},
	    {"bazel", TestResultFormat::BAZEL_BUILD},
	    {"visualstudio", TestResultFormat::MSBUILD},
	    {"vs", TestResultFormat::MSBUILD},
	    // Test framework aliases
	    {"gtest", TestResultFormat::GTEST_TEXT},
	    {"googletest", TestResultFormat::GTEST_TEXT},
	    {"rspec", TestResultFormat::RSPEC_TEXT},
	    {"mocha", TestResultFormat::MOCHA_CHAI_TEXT},
	    {"chai", TestResultFormat::MOCHA_CHAI_TEXT},
	    {"nunit", TestResultFormat::NUNIT_XUNIT_TEXT},
	    {"xunit", TestResultFormat::NUNIT_XUNIT_TEXT},
	    {"pytest", TestResultFormat::PYTEST_TEXT},
	    {"pytest_cov", TestResultFormat::PYTEST_COV_TEXT},
	    {"pytest-cov", TestResultFormat::PYTEST_COV_TEXT},
	    // Debugging aliases
	    {"gdb", TestResultFormat::GDB_LLDB},
	    {"lldb", TestResultFormat::GDB_LLDB},
	    {"coverage", TestResultFormat::COVERAGE_TEXT},
	    // JSON format aliases
	    {"go_test_json", TestResultFormat::GOTEST_JSON},
	    {"gotest", TestResultFormat::GOTEST_JSON},
	    {"eslint", TestResultFormat::ESLINT_JSON},
	};
	return map;
}

TestResultFormat StringToTestResultFormat(const std::string &str) {
	// Check for regexp: prefix (dynamic pattern matching)
	if (str.rfind("regexp:", 0) == 0)
		return TestResultFormat::REGEXP;

	auto &map = GetFormatMap();
	auto it = map.find(str);
	return it != map.end() ? it->second : TestResultFormat::UNKNOWN;
}

// Get canonical format name from enum (for registry lookup)
// Returns empty string if format is unknown/auto
std::string GetCanonicalFormatName(TestResultFormat format) {
	// Canonical names map enum to registry format name
	static const std::unordered_map<TestResultFormat, std::string> canonical_names = {
	    {TestResultFormat::PYTEST_JSON, "pytest_json"},
	    {TestResultFormat::GOTEST_JSON, "gotest_json"},
	    {TestResultFormat::ESLINT_JSON, "eslint_json"},
	    {TestResultFormat::PYTEST_TEXT, "pytest_text"},
	    {TestResultFormat::MAKE_ERROR, "make_error"},
	    {TestResultFormat::GCC_TEXT, "gcc_text"},
	    {TestResultFormat::GENERIC_LINT, "generic_lint"},
	    {TestResultFormat::DUCKDB_TEST, "duckdb_test"},
	    {TestResultFormat::RUBOCOP_JSON, "rubocop_json"},
	    {TestResultFormat::CARGO_TEST_JSON, "cargo_test_json"},
	    {TestResultFormat::SWIFTLINT_JSON, "swiftlint_json"},
	    {TestResultFormat::PHPSTAN_JSON, "phpstan_json"},
	    {TestResultFormat::SHELLCHECK_JSON, "shellcheck_json"},
	    {TestResultFormat::STYLELINT_JSON, "stylelint_json"},
	    {TestResultFormat::CLIPPY_JSON, "clippy_json"},
	    {TestResultFormat::MARKDOWNLINT_JSON, "markdownlint_json"},
	    {TestResultFormat::YAMLLINT_JSON, "yamllint_json"},
	    {TestResultFormat::BANDIT_JSON, "bandit_json"},
	    {TestResultFormat::SPOTBUGS_JSON, "spotbugs_json"},
	    {TestResultFormat::KTLINT_JSON, "ktlint_json"},
	    {TestResultFormat::HADOLINT_JSON, "hadolint_json"},
	    {TestResultFormat::LINTR_JSON, "lintr_json"},
	    {TestResultFormat::SQLFLUFF_JSON, "sqlfluff_json"},
	    {TestResultFormat::TFLINT_JSON, "tflint_json"},
	    {TestResultFormat::KUBE_SCORE_JSON, "kube_score_json"},
	    {TestResultFormat::CMAKE_BUILD, "cmake_build"},
	    {TestResultFormat::PYTHON_BUILD, "python_build"},
	    {TestResultFormat::NODE_BUILD, "node_build"},
	    {TestResultFormat::CARGO_BUILD, "cargo_build"},
	    {TestResultFormat::MAVEN_BUILD, "maven_build"},
	    {TestResultFormat::GRADLE_BUILD, "gradle_build"},
	    {TestResultFormat::MSBUILD, "msbuild"},
	    {TestResultFormat::JUNIT_TEXT, "junit_text"},
	    {TestResultFormat::VALGRIND, "valgrind"},
	    {TestResultFormat::GDB_LLDB, "gdb_lldb"},
	    {TestResultFormat::RSPEC_TEXT, "rspec_text"},
	    {TestResultFormat::MOCHA_CHAI_TEXT, "mocha_chai_text"},
	    {TestResultFormat::GTEST_TEXT, "gtest_text"},
	    {TestResultFormat::NUNIT_XUNIT_TEXT, "nunit_xunit_text"},
	    {TestResultFormat::PYLINT_TEXT, "pylint_text"},
	    {TestResultFormat::FLAKE8_TEXT, "flake8_text"},
	    {TestResultFormat::BLACK_TEXT, "black_text"},
	    {TestResultFormat::MYPY_TEXT, "mypy_text"},
	    {TestResultFormat::DOCKER_BUILD, "docker_build"},
	    {TestResultFormat::BAZEL_BUILD, "bazel_build"},
	    {TestResultFormat::ISORT_TEXT, "isort_text"},
	    {TestResultFormat::BANDIT_TEXT, "bandit_text"},
	    {TestResultFormat::AUTOPEP8_TEXT, "autopep8_text"},
	    {TestResultFormat::YAPF_TEXT, "yapf_text"},
	    {TestResultFormat::COVERAGE_TEXT, "coverage_text"},
	    {TestResultFormat::PYTEST_COV_TEXT, "pytest_cov_text"},
	    {TestResultFormat::GITHUB_ACTIONS_TEXT, "github_actions_text"},
	    {TestResultFormat::GITLAB_CI_TEXT, "gitlab_ci_text"},
	    {TestResultFormat::JENKINS_TEXT, "jenkins_text"},
	    {TestResultFormat::DRONE_CI_TEXT, "drone_ci_text"},
	    {TestResultFormat::TERRAFORM_TEXT, "terraform_text"},
	    {TestResultFormat::ANSIBLE_TEXT, "ansible_text"},
	    {TestResultFormat::GITHUB_CLI, "github_cli"},
	    {TestResultFormat::CLANG_TIDY_TEXT, "clang_tidy_text"},
	    {TestResultFormat::JUNIT_XML, "junit_xml"},
	    {TestResultFormat::NUNIT_XML, "nunit_xml"},
	    {TestResultFormat::CHECKSTYLE_XML, "checkstyle_xml"},
	    {TestResultFormat::JSONL, "jsonl"},
	    {TestResultFormat::LOGFMT, "logfmt"},
	    {TestResultFormat::SYSLOG, "syslog"},
	    {TestResultFormat::APACHE_ACCESS, "apache_access"},
	    {TestResultFormat::NGINX_ACCESS, "nginx_access"},
	    {TestResultFormat::AWS_CLOUDTRAIL, "aws_cloudtrail"},
	    {TestResultFormat::GCP_CLOUD_LOGGING, "gcp_cloud_logging"},
	    {TestResultFormat::AZURE_ACTIVITY, "azure_activity"},
	    {TestResultFormat::PYTHON_LOGGING, "python_logging"},
	    {TestResultFormat::LOG4J, "log4j"},
	    {TestResultFormat::LOGRUS, "logrus"},
	    {TestResultFormat::IPTABLES, "iptables"},
	    {TestResultFormat::PF_FIREWALL, "pf"},
	    {TestResultFormat::CISCO_ASA, "cisco_asa"},
	    {TestResultFormat::VPC_FLOW, "vpc_flow"},
	    {TestResultFormat::KUBERNETES, "kubernetes"},
	    {TestResultFormat::WINDOWS_EVENT, "windows_event"},
	    {TestResultFormat::AUDITD, "auditd"},
	    {TestResultFormat::S3_ACCESS, "s3_access"},
	    {TestResultFormat::WINSTON, "winston"},
	    {TestResultFormat::PINO, "pino"},
	    {TestResultFormat::BUNYAN, "bunyan"},
	    {TestResultFormat::SERILOG, "serilog"},
	    {TestResultFormat::NLOG, "nlog"},
	    {TestResultFormat::RUBY_LOGGER, "ruby_logger"},
	    {TestResultFormat::RAILS_LOG, "rails_log"},
	    {TestResultFormat::STRACE, "strace"},
	    {TestResultFormat::GCC_TEXT, "gcc_text"},
	};
	auto it = canonical_names.find(format);
	return it != canonical_names.end() ? it->second : "";
}

} // namespace duckdb
